# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170712_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='object_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='exception',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.RuleException'),
            preserve_default=False,
        ),
    ]
