# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20170712_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='exception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.RuleException'),
        ),
    ]
