# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20170712_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='exception',
        ),
    ]
