# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_answer_exception'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='exception',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.RuleException'),
            preserve_default=False,
        ),
    ]
